# permissions for end users to edit metalnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metalnode-editor-role
rules:
- apiGroups:
  - metal.metal.node
  resources:
  - metalnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.metal.node
  resources:
  - metalnodes/status
  verbs:
  - get
